In [1]:
import numpy as np

### Scalars 
For example, $n \in \mathbb{N}$ or $s \in \mathbb{R}$

In [2]:
n = 3
s = 4.67

### Vectors
$\boldsymbol{x} = \begin{bmatrix}x_{1} \\ x_{2} \\ \vdots \\ x_{n}\end{bmatrix}$

In [59]:
x = np.array([[2],
              [3],
              [5],
              [7],
              [11],
              [13]])
print(x)
print("\nshape:",x.shape)

[[ 2]
 [ 3]
 [ 5]
 [ 7]
 [11]
 [13]]

shape: (6, 1)


$x_{i} = x_{i,j}$

In [60]:
print(x[5][0])

13


#### Transpose
$x^\top = [x_{1}, x_{2}, ..., x_{3}]$

In [62]:
print(x.T)
print("\nshape:",x.T.shape)

[[ 2  3  5  7 11 13]]

shape: (1, 6)


### Matrices
$\boldsymbol{A} \in \mathbb{R}^{m \times n}$

For example, $\boldsymbol{A} \in \mathbb{R}^{2 \times 3}$

$\boldsymbol{A} = \begin{bmatrix}A_{1,1} & A_{1,2} & A_{1,3} \\ A_{2,1} & A_{2,2} & A_{2,3}\end{bmatrix}$

In [43]:
A = np.array([[2,3,5],
              [7,11,13]])
print(A)
print("\nshape:",A.shape)

[[ 2  3  5]
 [ 7 11 13]]

shape: (2, 3)


$A_{i,j}$

In [44]:
print(A[1][2])

13


In [63]:
A = np.matrix('2 3 5; 7 11 13')
print(A)
print("\nshape:",A.shape)

[[ 2  3  5]
 [ 7 11 13]]

shape: (2, 3)


In [46]:
print(A.item(1,2))

13


#### Transpose
$(\boldsymbol{A}^\top)_{i,j} = A_{j,i}$

$\boldsymbol{A} \implies \boldsymbol{A}^\top = \begin{bmatrix}A_{1,1} & A_{2,1} \\ A_{1,2} & A_{2,2} \\ A_{1,3} & A_{2,3}\end{bmatrix} = \begin{bmatrix}A^\top_{1,1} & A^\top_{1,2} \\ A^\top_{2,1} & A^\top_{2,2} \\ A^\top_{3,1} & A^\top_{3,2}\end{bmatrix}$

In [65]:
print(A.T)
print("\nshape:",A.T.shape)

[[ 2  7]
 [ 3 11]
 [ 5 13]]

shape: (3, 2)


### Tensors

$\textsf{A} \in \mathbb{R}^{m \times n \times o}$

For example, $\textsf{A} \in \mathbb{R}^{2 \times 3 \times 2}$

In [47]:
A = np.array([2,3,5,7,11,13,2,4,6,8,10,12]).reshape(2,3,2)
print(A)
print("\nshape:",A.shape)

[[[ 2  3]
  [ 5  7]
  [11 13]]

 [[ 2  4]
  [ 6  8]
  [10 12]]]

shape: (2, 3, 2)


In [50]:
A = np.array([[[2, 3],
               [5, 7],
               [11, 13]],
              [[2, 4],
               [6, 8],
               [10, 12]]])
print(A)
print("\nshape:",A.shape)

[[[ 2  3]
  [ 5  7]
  [11 13]]

 [[ 2  4]
  [ 6  8]
  [10 12]]]

shape: (2, 3, 2)


$\textsf{A}_{i,j,k}$

In [57]:
print(A[0][2][1])

13


### Matrix Addition
$\boldsymbol{C} = \boldsymbol{A} + \boldsymbol{B}$, where $C_{i,j} = A_{i,j} + B_{i,j}$

In [67]:
A = np.matrix('2 3 5; 7 11 13')
B = np.matrix('2 4 6; 8 10 12')
C = A + B
print(C)
print("\nshape:",C.shape)

[[ 4  7 11]
 [15 21 25]]

shape: (2, 3)
